import Head from 'next/head';

interface LayoutProps {
  children: JSX.Element
}

const Layout = ({ children }: LayoutProps) => {
  return (
      <>
        <Head>
          <title key="title">TacoBot</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>{children}</main>
      </>
    )
};

export default Layout;